# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  env:
    CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
    CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
  inputs:
    script: 
      echo $(CHKP_CLOUDGUARD_ID)
  displayName: Showing ID
- task: CmdLine@2
  env:
    CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
    CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)  
  inputs:
      script: |
        git clone https://github.com/chkp-nchao/cloudguard-iac-noncompliant-terraform
        ./shiftleft iac-assessment -p ./cloudguard-iac-noncompliant-terraform/aws/ -r -64
  displayName: Running Terraform Assessment

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'